---
language: ruby
cache: bundler

# necessary for docker to work
sudo: required
dist: trusty
services:
  - docker

matrix:
  include:
    - rvm: 2.2
      bundler_args: "--without integration"
      script: bundle exec rake
