---
branches:
  only:
    - master
language: ruby
cache: bundler

# necessary for docker to work
sudo: required
dist: trusty
services:
  - docker

before_install:
  - gem install bundler
  - gem --version

matrix:
  include:
  - rvm: 2.2
    script: bundle exec rake
  - rvm: 2.3.1
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='default-centos-7'
  - rvm: 2.3.1
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='default-ubuntu-1404'
